# Generated by Django 4.2.5 on 2023-09-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=20)),
                ('client_contact', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('booked_event_type', models.CharField(max_length=20)),
                ('booked_date_of_event', models.DateField()),
                ('booked_event_time', models.TimeField()),
                ('booked_event_location', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('event_type', models.CharField(max_length=20)),
                ('date_of_event', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('pricing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('transaction_id', models.IntegerField(max_length=20)),
                ('amount', models.IntegerField(max_length=11)),
                ('transaction_date', models.DateField(max_length=20)),
                ('transaction_time', models.TimeField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
